// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/nats"
	"github.com/995933447/memcache/memcache"
	"github.com/995933447/memcache/memcacheserver/handler"
)

func RegisterNatsRPCRoutes() error {
	var err error

	err = nats.HandleLikeGRPC(memcache.EasymicroGRPCPbServiceNameMemCache, "Get", handler.MemCacheHandler.Get, func() *memcache.GetReq {
		return &memcache.GetReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(memcache.EasymicroGRPCPbServiceNameMemCache, "Set", handler.MemCacheHandler.Set, func() *memcache.SetReq {
		return &memcache.SetReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(memcache.EasymicroGRPCPbServiceNameMemCache, "Del", handler.MemCacheHandler.Del, func() *memcache.DelReq {
		return &memcache.DelReq{}
	})
	if err != nil {
		return err
	}

	return nil
}
