// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/memcache/memcache"
	"github.com/995933447/memcache/memcacheserver/handler"
	"google.golang.org/grpc"
)

var ServiceNames = []string{
	memcache.EasymicroGRPCPbServiceNameMemCache,
}

var RegisterServiceServers = func(server *grpc.Server) error {
	memcache.RegisterMemCacheServer(server, handler.MemCacheHandler)
	return nil
}
