// Code generated by protoc-gen-easymicro-client. DO NOT EDIT.
package configimage

import (
	"sync"

	easymicrogrpc "github.com/995933447/easymicro/grpc"
	"context"
	"google.golang.org/grpc"
)

const (
	EasymicroGRPCSchema    = "mconfigcenterimg"
	EasymicroDiscoveryName = "mconfigcenter_img"
)

const EasymicroGRPCPbServiceNameConfigImage = "configimage.ConfigImage"

var ConfigImageDefault = &ConfigImage{}

func ConfigImageGRPC() *ConfigImage {
	return ConfigImageDefault
}

func NewConfigImageGRPC(dialOpts ...grpc.DialOption) *ConfigImage {
	return &ConfigImage{
		dialOpts: dialOpts,
	}
}

type ConfigImage struct {
	c        ConfigImageClient
	conn     *grpc.ClientConn
	once     sync.Once
	mu       sync.RWMutex
	dialOpts []grpc.DialOption
}

func (s *ConfigImage) Close() error {
	err := s.conn.Close()
	if err != nil {
		return err
	}
	return nil
}

func (s *ConfigImage) prepareConn() error {
	var err error
	s.once.Do(func() {
		var conn *grpc.ClientConn
		opts := s.dialOpts
		if opts == nil {
			opts = easymicrogrpc.BuildServiceDialOpts(EasymicroGRPCPbServiceNameConfigImage)
		}
		conn, err = grpc.NewClient(EasymicroGRPCSchema+":///"+EasymicroGRPCPbServiceNameConfigImage, opts...)
		if err != nil {
			return
		}
		s.conn = conn
		s.c = NewConfigImageClient(conn)
	})
	if err != nil {
		return err
	}
	return nil
}

func (s *ConfigImage) ListConfig(ctx context.Context, in *ListConfigReq, opts ...grpc.CallOption) (*ListConfigResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ListConfig(ctx, in, opts...)
}

func (s *ConfigImage) GetKeyValue(ctx context.Context, in *GetKeyValueReq, opts ...grpc.CallOption) (*GetKeyValueResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.GetKeyValue(ctx, in, opts...)
}
