// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: memcache.proto

package memcache

import (
	_ "github.com/995933447/easymicro/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_ErrCodeNil                   ErrCode = 0
	ErrCode_ErrCodeParamInvalid          ErrCode = 2001
	ErrCode_ErrCodeCtxKeyHashKeyNotFound ErrCode = 2002
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:    "ErrCodeNil",
		2001: "ErrCodeParamInvalid",
		2002: "ErrCodeCtxKeyHashKeyNotFound",
	}
	ErrCode_value = map[string]int32{
		"ErrCodeNil":                   0,
		"ErrCodeParamInvalid":          2001,
		"ErrCodeCtxKeyHashKeyNotFound": 2002,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_memcache_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_memcache_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_memcache_proto_rawDescGZIP(), []int{0}
}

type GetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_memcache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_memcache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_memcache_proto_rawDescGZIP(), []int{0}
}

func (x *GetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResp) Reset() {
	*x = GetResp{}
	mi := &file_memcache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResp) ProtoMessage() {}

func (x *GetResp) ProtoReflect() protoreflect.Message {
	mi := &file_memcache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResp.ProtoReflect.Descriptor instead.
func (*GetResp) Descriptor() ([]byte, []int) {
	return file_memcache_proto_rawDescGZIP(), []int{1}
}

func (x *GetResp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReq) Reset() {
	*x = SetReq{}
	mi := &file_memcache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReq) ProtoMessage() {}

func (x *SetReq) ProtoReflect() protoreflect.Message {
	mi := &file_memcache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReq.ProtoReflect.Descriptor instead.
func (*SetReq) Descriptor() ([]byte, []int) {
	return file_memcache_proto_rawDescGZIP(), []int{2}
}

func (x *SetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResp) Reset() {
	*x = SetResp{}
	mi := &file_memcache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResp) ProtoMessage() {}

func (x *SetResp) ProtoReflect() protoreflect.Message {
	mi := &file_memcache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResp.ProtoReflect.Descriptor instead.
func (*SetResp) Descriptor() ([]byte, []int) {
	return file_memcache_proto_rawDescGZIP(), []int{3}
}

type DelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelReq) Reset() {
	*x = DelReq{}
	mi := &file_memcache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelReq) ProtoMessage() {}

func (x *DelReq) ProtoReflect() protoreflect.Message {
	mi := &file_memcache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelReq.ProtoReflect.Descriptor instead.
func (*DelReq) Descriptor() ([]byte, []int) {
	return file_memcache_proto_rawDescGZIP(), []int{4}
}

func (x *DelReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelResp) Reset() {
	*x = DelResp{}
	mi := &file_memcache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelResp) ProtoMessage() {}

func (x *DelResp) ProtoReflect() protoreflect.Message {
	mi := &file_memcache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelResp.ProtoReflect.Descriptor instead.
func (*DelResp) Descriptor() ([]byte, []int) {
	return file_memcache_proto_rawDescGZIP(), []int{5}
}

var File_memcache_proto protoreflect.FileDescriptor

const file_memcache_proto_rawDesc = "" +
	"\n" +
	"\x0ememcache.proto\x12\bmemcache\x1a\x13easymicro_ext.proto\"\x1a\n" +
	"\x06GetReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"/\n" +
	"\aGetResp\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"0\n" +
	"\x06SetReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\t\n" +
	"\aSetResp\"\x1a\n" +
	"\x06DelReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\t\n" +
	"\aDelResp*V\n" +
	"\aErrCode\x12\x0e\n" +
	"\n" +
	"ErrCodeNil\x10\x00\x12\x18\n" +
	"\x13ErrCodeParamInvalid\x10\xd1\x0f\x12!\n" +
	"\x1cErrCodeCtxKeyHashKeyNotFound\x10\xd2\x0f2\x8e\x01\n" +
	"\bMemCache\x12*\n" +
	"\x03Get\x12\x10.memcache.GetReq\x1a\x11.memcache.GetResp\x12*\n" +
	"\x03Set\x12\x10.memcache.SetReq\x1a\x11.memcache.SetResp\x12*\n" +
	"\x03Del\x12\x10.memcache.DelReq\x1a\x11.memcache.DelRespBL\x8a\x9d \x1b \x01@\x01Z\bmemcacheb\bmemcache\x88\x01\x01Z+github.com/995933447/mconfigcenter/memcacheb\x06proto3"

var (
	file_memcache_proto_rawDescOnce sync.Once
	file_memcache_proto_rawDescData []byte
)

func file_memcache_proto_rawDescGZIP() []byte {
	file_memcache_proto_rawDescOnce.Do(func() {
		file_memcache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memcache_proto_rawDesc), len(file_memcache_proto_rawDesc)))
	})
	return file_memcache_proto_rawDescData
}

var file_memcache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_memcache_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_memcache_proto_goTypes = []any{
	(ErrCode)(0),    // 0: memcache.ErrCode
	(*GetReq)(nil),  // 1: memcache.GetReq
	(*GetResp)(nil), // 2: memcache.GetResp
	(*SetReq)(nil),  // 3: memcache.SetReq
	(*SetResp)(nil), // 4: memcache.SetResp
	(*DelReq)(nil),  // 5: memcache.DelReq
	(*DelResp)(nil), // 6: memcache.DelResp
}
var file_memcache_proto_depIdxs = []int32{
	1, // 0: memcache.MemCache.Get:input_type -> memcache.GetReq
	3, // 1: memcache.MemCache.Set:input_type -> memcache.SetReq
	5, // 2: memcache.MemCache.Del:input_type -> memcache.DelReq
	2, // 3: memcache.MemCache.Get:output_type -> memcache.GetResp
	4, // 4: memcache.MemCache.Set:output_type -> memcache.SetResp
	6, // 5: memcache.MemCache.Del:output_type -> memcache.DelResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_memcache_proto_init() }
func file_memcache_proto_init() {
	if File_memcache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memcache_proto_rawDesc), len(file_memcache_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memcache_proto_goTypes,
		DependencyIndexes: file_memcache_proto_depIdxs,
		EnumInfos:         file_memcache_proto_enumTypes,
		MessageInfos:      file_memcache_proto_msgTypes,
	}.Build()
	File_memcache_proto = out.File
	file_memcache_proto_goTypes = nil
	file_memcache_proto_depIdxs = nil
}
