// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.2
// source: memcache.proto

package memcache

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemCache_Get_FullMethodName = "/memcache.MemCache/Get"
	MemCache_Set_FullMethodName = "/memcache.MemCache/Set"
	MemCache_Del_FullMethodName = "/memcache.MemCache/Del"
)

// MemCacheClient is the client API for MemCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MemCacheClient interface {
	// 获取缓存
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error)
	// 设置缓存
	Set(ctx context.Context, in *SetReq, opts ...grpc.CallOption) (*SetResp, error)
	// 删除缓存
	Del(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*DelResp, error)
}

type memCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewMemCacheClient(cc grpc.ClientConnInterface) MemCacheClient {
	return &memCacheClient{cc}
}

func (c *memCacheClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResp)
	err := c.cc.Invoke(ctx, MemCache_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memCacheClient) Set(ctx context.Context, in *SetReq, opts ...grpc.CallOption) (*SetResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResp)
	err := c.cc.Invoke(ctx, MemCache_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memCacheClient) Del(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*DelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelResp)
	err := c.cc.Invoke(ctx, MemCache_Del_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemCacheServer is the server API for MemCache service.
// All implementations must embed UnimplementedMemCacheServer
// for forward compatibility.
type MemCacheServer interface {
	// 获取缓存
	Get(context.Context, *GetReq) (*GetResp, error)
	// 设置缓存
	Set(context.Context, *SetReq) (*SetResp, error)
	// 删除缓存
	Del(context.Context, *DelReq) (*DelResp, error)
	mustEmbedUnimplementedMemCacheServer()
}

// UnimplementedMemCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemCacheServer struct{}

func (UnimplementedMemCacheServer) Get(context.Context, *GetReq) (*GetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMemCacheServer) Set(context.Context, *SetReq) (*SetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedMemCacheServer) Del(context.Context, *DelReq) (*DelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Del not implemented")
}
func (UnimplementedMemCacheServer) mustEmbedUnimplementedMemCacheServer() {}
func (UnimplementedMemCacheServer) testEmbeddedByValue()                  {}

// UnsafeMemCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemCacheServer will
// result in compilation errors.
type UnsafeMemCacheServer interface {
	mustEmbedUnimplementedMemCacheServer()
}

func RegisterMemCacheServer(s grpc.ServiceRegistrar, srv MemCacheServer) {
	// If the following call pancis, it indicates UnimplementedMemCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemCache_ServiceDesc, srv)
}

func _MemCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemCache_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemCacheServer).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemCache_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemCacheServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemCache_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemCacheServer).Set(ctx, req.(*SetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemCache_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemCacheServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemCache_Del_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemCacheServer).Del(ctx, req.(*DelReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MemCache_ServiceDesc is the grpc.ServiceDesc for MemCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memcache.MemCache",
	HandlerType: (*MemCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _MemCache_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _MemCache_Set_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _MemCache_Del_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "memcache.proto",
}
