// Code generated by protoc-gen-easymicro-client. DO NOT EDIT.
package memcache

import (
	"sync"

	easymicrogrpc "github.com/995933447/easymicro/grpc"
	"context"
	"google.golang.org/grpc"
)

const (
	EasymicroGRPCSchema    = "memcache"
	EasymicroDiscoveryName = "memcache"
)

const EasymicroGRPCPbServiceNameMemCache = "memcache.MemCache"

var MemCacheDefault = &MemCache{}

func MemCacheGRPC() *MemCache {
	return MemCacheDefault
}

func NewMemCacheGRPC(dialOpts ...grpc.DialOption) *MemCache {
	return &MemCache{
		dialOpts: dialOpts,
	}
}

type MemCache struct {
	c        MemCacheClient
	conn     *grpc.ClientConn
	once     sync.Once
	mu       sync.RWMutex
	dialOpts []grpc.DialOption
}

func (s *MemCache) Close() error {
	err := s.conn.Close()
	if err != nil {
		return err
	}
	return nil
}

func (s *MemCache) prepareConn() error {
	var err error
	s.once.Do(func() {
		var conn *grpc.ClientConn
		opts := s.dialOpts
		if opts == nil {
			opts = easymicrogrpc.BuildServiceDialOpts(EasymicroGRPCPbServiceNameMemCache)
		}
		conn, err = grpc.NewClient(EasymicroGRPCSchema+":///"+EasymicroGRPCPbServiceNameMemCache, opts...)
		if err != nil {
			return
		}
		s.conn = conn
		s.c = NewMemCacheClient(conn)
	})
	if err != nil {
		return err
	}
	return nil
}

func (s *MemCache) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.Get(ctx, in, opts...)
}

func (s *MemCache) Set(ctx context.Context, in *SetReq, opts ...grpc.CallOption) (*SetResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.Set(ctx, in, opts...)
}

func (s *MemCache) Del(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*DelResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.Del(ctx, in, opts...)
}
